
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend-python
      dockerfile: Dockerfile
    container_name: backend_api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/app_db
      - PROJECT_NAME=API
      - PROJECT_VERSION=1.0.0
      - PROJECT_DESCRIPTION=API do Projeto
      - FRONTEND_URL=http://localhost:4200
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      
      # Configurações de E-mail
      - MAIL_USERNAME=antoniocarelli@gmail.com
      - MAIL_PASSWORD=ckyschegrvnfpwsa
      - MAIL_FROM=app@gmail.com
      - MAIL_PORT=587
      - MAIL_SERVER=smtp.gmail.com
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend-python/src:/app
    command: uvicorn app.services.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend-angular
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "4200:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://localhost:8000

volumes:
  postgres_data: 